# Site settings
title: Frank the Obscure
brief-intro: 无名的弗兰克
email: humour114@gmail.com
url: "http://frank-the-obscure.me"

permalink: /:year/:month/:day/:title/

# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: mofhu
zhihu_username: frank_hu
linkedIn_username: mofrankhu
permalink: /:year/:month/:day/:title/

description_footer: Frank the Obscure 无名的弗兰克 - 一只有点迷茫的化学狗
# comments
# two ways to comment, only choose one, and use your own short name
disqus_shortname: frank-the-obscure

# statistic analysis 统计代码
google_analytics_id: UA-79882228-1 # google 分析追踪id



# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed #:expanded # You might prefer to minify using :compressed

# highlight
highlighter: rouge

# excerpt
excerpt_separator: "\n\n\n\n"

# url
category_dir: category/
tag_dir: tag/

# paginate
gems: [jekyll-paginate]
paginate: 5

# able to build "future" posts
future: true
